### PR TITLE
Fix bug with pasting hex (#330)

### LINKED ISSUE #330: Doesn't handle hash correctly
### Description

> When the text has the "#" the color is 000000 instead of deleting the "#".

_Originally posted by @RIMOPA in https://github.com/ScratchAddons/ScratchAddons/issues/2096#issuecomment-1138038371_

This bug has been bugging me for a while, but I never reported it.

### Reproduction steps

1. Open the settings page or pop-up
2. Expand an addon with a colour picker
3. Paste a hex colour with a hash

### Expected behavior

It should remove the hash leaving just the 6 hex digits

### Actual behavior

The hex digits are pushed one over one deleting the last one resulting in somthing like `#ff7b2` and since it's an invalid value, pressing enter just results in the fallback colour (pure black)

### Screenshots

https://user-images.githubusercontent.com/81489795/170506835-7e6a3b81-9843-4fa0-95d4-15891632a4c4.mp4

### Environment

- Browser: Firefox
- Scratch Addons version: 1.26.0 (happened in older versions too)
- Operating system: Ubuntu 22.04 LTS

_Originally posted by @Samq64 in https://github.com/ScratchAddons/ScratchAddons/issues/4611_

### PR DESCRIPTION
**Pull request by Norbiros**
Fixes #330
Continuation of https://github.com/ScratchAddons/ScratchAddons/pull/4612

### CODE REVIEW

File: src/color-picker.js [hunk 1]
```diff
@@ -585,9 +590,24 @@ class ColorPicker extends PropertiesChangedHandler(PropertiesChangedCallback(Pro
...
+    if(!this._pointerDown) return;
+
+    const {x, y} = this.getBoundingClientRect();
+    const pointerX = Math.round(e.clientX - x);
+    const pointerY = Math.round(e.clientY - y);
+    const saturation = Math.min(Math.max((pointerX / this._$grid.offsetWidth), 0), 1.00);
+    const value = 1.00 - Math.min(Math.max((pointerY / this._$grid.offsetHeight), 0), 1.00);
+    
+    if(this.selectedFormat === 'hsl') this.value = {...this.color.toHsl(), ...{s: saturation}, ...{l: value}};
+    else this.value = {...this.color.toHsv(), ...{s: saturation}, ...{v: value}};
```
Comment (GrahamSH-LLK) [inline src/color-picker.js:610]: How is this change related?

**Comment by Norbiros** [comment]
@GrahamSH-LLK Can you also close  ScratchAddons/ScratchAddons#4611 ?

**Comment by GrahamSH-LLK** [comment]
Once I run the build process and PR to SA sure
